animals = ['lion', 'tiger', 'cat', 'dog']
animals.sort()
print(animals)
animals.append('rabbit')
print(animals)
animals.reverse()
print(animals)
s = animals.pop()
print(s)
print(s.upper())
print(s.find('a'))
